<?php
/**
 * Created by PhpStorm.
 * User: Ivan
 * Date: 02/11/2017
 * Time: 10:27 AM
 */


function traductorSwitch($semaforo){

    switch($semaforo){
        case 1:
            return "si";
            break;
        case 2:
            return "no";
            break;
        case 3:
            return "nc";
            break;
        default:
            return "nc";
            break;
    }
}

function traductorEscuela($escuelaNumero){

    $escuela = array(
        'OTRA ESCUELA',
        'ESC. ED.SECUNDARIA "PROCESA SARMIENTO DE LENOIR" - 9 DE JULIO ',
        'Prof. Ana PEREZ CIANI - 9 DE JULIO ',
        'CENTRO POLIVALENTE DE ARTE - CAPITAL ',
        'COLEGIO NACIONAL MONS. DR. PABLO CABRERA - CAPITAL ',
        'COLEGIO PROVINCIAL CONCEPCION - CAPITAL ',
        'COLEGIO PROVINCIAL DE CAPITAL - CAPITAL ',
        'E.P.E.T. N° 1 ING. ROGELIO BOERO - CAPITAL ',
        'E.P.E.T. N° 2 - CAPITAL ',
        'E.P.E.T. N° 4 - CAPITAL ',
        'E.P.E.T. N° 5 - CAPITAL ',
        'ESC.ED. SECUNDARIA "DR. FRANCISCO NARCISO LAPRIDA" - CAPITAL ',
        'ESCUELA DE COMERCIO GRAL. MANUEL BELGRANO - CAPITAL ',
        'ESCUELA DE EGB 3 Y POLIMODAL 9 DE JULIO - CAPITAL ',
        'ESCUELA DE FRUTICULTURA Y ENOLOGIA - CAPITAL ',
        'ESCUELA SECUNDARIA "ESTEBAN ECHEVERRIA" - CAPITAL ',
        'ESCUELA SECUNDARIA MIGUEL DE AZCUENAGA - CAPITAL ',
        'ESCUELA TECNICA OBRERO ARGENTINO - CAPITAL ',
        'LICEO PAULA ALBARRACIN DE SARMIENTO - CAPITAL ',
        'Colegio de Educación General Básica 3 y Polimodal “Gral. San Martín” - CHIMBAS ',
        'Colegio Dr. Manuel Alvar López - CHIMBAS ',
        'COLEGIO PROVINCIAL DE CHIMBAS I - CHIMBAS ',
        'Colegio Secundario Jorge Luis Borges - CHIMBAS ',
        'ESCUELA DE EDUCACIÓN SECUNDARIA "PRESIDENTE DR. ARTURO UMBERTO ILLIA" - CHIMBAS ',
        'ESCUELA SECUNDARIA "ARTURO CAPDEVILA" - CHIMBAS ',
        'COLEGIO PROVINCIAL DE SANTA LUCIA - SANTA LUCIA ',
        'COLEGIO SECUNDARIO JUAN PABLO ECHAGUE - SANTA LUCIA ',
        'E.P.E.T. N° 8  SAN JUAN - SANTA LUCIA ',
        'ESCUELA DE EDUCACION SECUNDARIA CARLOS PELLEGRINI - SANTA LUCIA ',
        'AGROINDUSTRIAL 25 DE MAYO - 25 DE MAYO ',
        'ESCUELA DE EDUCACION SECUNDARIA CTE. TOMAS ESPORA - 25 DE MAYO ',
        'ESCUELA SECUNDARIA MARTIN YANZON - 25 DE MAYO ',
        'SEGUNDINO J. NAVARRO EGB 3 Y POLIMODAL - 25 DE MAYO ',
        'COLEGIO SECUNDARIO CACIQUE ANGACO - ANGACO ',
        'ESCUELA DE EDUCACIÓN SECUNDARIA "PROVINCIA DE NEUQUÉN" - SAN MARTIN ',
        'ESCUELA SECUNDARIA ALEJANDRO MARIA DE AGUADO - SAN MARTIN ',
        'AGROTECNICA EJERCITO ARGENTINO - VALLE FERTIL ',
        'COLEGIO SUPERIOR N° 1 FUERZA AEREA ARGENTINA - VALLE FERTIL ',
        'EGB3 Y POLIMODAL ASTICA - VALLE FERTIL ',
        'E.P.E.T. N° 1 CAUCETE - CAUCETE ',
        'ESCUELA DE COMERCIO ALFONSINA STORNI - CAUCETE ',
        'ESCUELA SECUNDARIA "HIPOLITO VIEYTES" - CAUCETE ',
        'ESCUELA SECUNDARIA "LEONOR SANCHEZ DE ARANCIBIA" - CAUCETE ',
        'ESCUELA SECUNDARIA "OBISPO ZAPATA" - CAUCETE ',
        'GONZALO ALBERTO DOBLAS - CAUCETE ',
        'COLEGIO SECUNDARIO GRAL.DON TORIBIO DE LUZURIAGA - ALBARDON ',
        'E.P.E.T. N° 1 ALBARDON - ALBARDON ',
        'Presidente Néstor Carlos KIRCHNER - ALBARDON ',
        'BACHILLERATO COLUMNA CABOT - IGLESIA ',
        'C.E.N.S. RODEO IGLESIA - IGLESIA ',
        'ESCUELA AGROTECNICA CORNELIO SAAVEDRA - IGLESIA ',
        'AGROINDUSTRIAL MONS.DR.JUAN A.VIDELA CUELLO - JACHAL ',
        'AGROTECNICA DR. MANUEL BELGRANO - JACHAL ',
        'AGROTECNICA HUACO - JACHAL ',
        'E.P.E.T. N° 1 JACHAL - JACHAL ',
        'ESCUELA DE COMERCIO EUSEBIO DE JESUS DOJORTI - JACHAL ',
        'ESCUELA DE NIVEL MEDIO DE NIQUIVIL - JACHAL ',
        'ESCUELA DE NIVEL MEDIO PAMPA VIEJA - JACHAL ',
        'COLEGIO SECUNDARIO DE BARREAL - CALINGASTA ',
        'COLEGIO SECUNDARIO DE TAMBERIAS - CALINGASTA ',
        'ESCUELA TECNICA GRAL. MANUEL SAVIO - CALINGASTA ',
        'BACHILLERATO JOSE MANUEL ESTRADA - RIVADAVIA ',
        'C.E.N.S. RIM 22 - RIVADAVIA ',
        'COLEGIO PROVINCIAL Bº PARQUE RIVADAVIA NORTE - RIVADAVIA ',
        'COLEGIO PROVINCIAL DE RIVADAVIA - RIVADAVIA ',
        'COLEGIO SECUNDARIO DR. DIEGO DE SALINAS - RIVADAVIA ',
        'E.P.E.T. N° 6 LA BEBIDA - RIVADAVIA ',
        'E.P.E.T. N° 7 BARRIO ARAMBURU - RIVADAVIA ',
        'ESC.DE EGB3 Y POL. GRAL. DE LA NAC. ING.E. MOSCONI - RIVADAVIA ',
        'ESCUELA DE COMERCIO NICOLAS ECHEZARRETA - RIVADAVIA ',
        'ESCUELA DE EDUCACIÓN SECUNDARIA "BARRIO NUEVO CUYO" - RIVADAVIA ',
        'ESCUELA DE EDUCACION SECUNDARIA JULIA LEON - RIVADAVIA ',
        'PROVINCIA DE TUCUMAN - RIVADAVIA ',
        'PROVINCIA DE TUCUMAN - RIVADAVIA ',
        'E.P.E.T. Nº 9 Dr. RENÉ FAVALORO (Bachillerato Técnico “Ullum”) - ULLUM ',
        'AGROTECNICA ZONDA - ZONDA ',
        'AGROTECNICA SARMIENTO - SARMIENTO ',
        'ENRIQUE LARRETA - SARMIENTO ',
        'ESC. VICTORINA LENOIR DE NAVARRO - SARMIENTO ',
        'ESCUELA DE NIVEL SECUNDARIO LOS BERROS - SARMIENTO ',
        'ESCUELA EXPERIMENTAL DE NIVEL MEDIO DIVISADERO - SARMIENTO ',
        'SECUNDARIA JUAN EUGENIO SERU - SARMIENTO ',
        'COLEGIO SECUNDARIO PROFESOR FROILAN JAVIER FERRERO - POCITO ',
        'ESCUELA COMERCIO SIXTO SALINAS DE RIVERA - POCITO ',
        'ESCUELA DE EDUCACION SECUNDARIA JOSE MARIA TORRES - POCITO ',
        'ESCUELA DE EGB3 Y POLIMODAL ESPAÑA - POCITO ',
        'ESCUELA SECUNDARIA "JUSTO JOSE DE URQUIZA" - POCITO ',
        'SECUNDARIA JORGE WASHINGTON - POCITO ',
        'COL. SEC. CAP. DE FRAGATA CARLOS MARIA MOYANO - RAWSON ',
        'COLEGIO SECUNDARIO ANTONIO DE LA TORRE - RAWSON ',
        'Colegio Superior Nº 1 de Rawson, Profesora IOLE LEBE PALMOLELLI DE MASCOTTI - RAWSON ',
        'E.P.E.T. N° 3  SAN JUAN - RAWSON ',
        'ESC. DE EDUCACION SECUNDARIA PATRICIAS MENDOCINAS - RAWSON ',
        'ESCUELA AGROTECNICA LOS PIONEROS - RAWSON ',
        'ESCUELA SECUNDARIA "ALAS ARGENTINAS" - RAWSON ',
        'ESCUELA SECUNDARIA "JOSE MANUEL ESTRADA" - RAWSON ',
        'ESCUELA SECUNDARIA JUAN XXIII - RAWSON ',
        'ESCUELA SECUNDARIA PRESIDENTE SARMIENTO - RAWSON ',
        'EUGENIA BELIN SARMIENTO - RAWSON '


    );

    return $escuela[$escuelaNumero];
}

function traductorSexo($sexo){

    switch($sexo){
        case 'F':
            return "Femenino";
            break;
        case 'M':
            return "Masculino";
            break;
        default:
            return "Femenino";
            break;
    }
}

function traductorDepartamento($deptoNumero){

    $deptos = array(

        0 => 'OTRO',
        412 => '25 de Mayo',
        413 => '9 de Julio',
        414 => 'Albardón',
        415 => 'Angaco',
        416 => 'Calingasta',
        417 => 'Capital',
        418 => 'Caucete',
        419 => 'Chimbas',
        420 => 'Iglesia',
        421 => 'Jáchal',
        422 => 'Pocito',
        423 => 'Rawson',
        424 => 'Rivadavia',
        425 => 'San Martín',
        426 => 'Santa Lucía',
        427 => 'Sarmiento',
        428 => 'Ullúm',
        429 => 'Valle Fértil',
        430 => 'Zonda'
    );

    return $deptos[$deptoNumero];


}

function traductorLocalidad($locNumero){

    $loc = array(
        0=>'OTRA',
        2=>'25 DE MAYO',
        3=>'CAMARICO',
        4=>'CHILCAS',
        5=>'DIVISORIA',
        6=>'EL CHAÑAR',
        7=>'ENCRUCIJADA',
        8=>'ESTACION ALGARROBO VERDE',
        9=>'CHIMBERA',
        10=>'LAS CASUARINAS',
        11=>'RAWSON',
        12=>'VILLA BORJAS - LA CHIMBERA',
        3186=>'EL ENCON',
        3187=>'TUPELI',
        3188=>'VILLA EL TANGO',
        3189=>'VILLA SANTA ROSA',
        3190=>'PASCUAL CHENA',
        3191=>'LA TRANCA',
        3192=>'ESTACION PUNTA DEL AGUA',
        4538=>'LA CHIMBERA',
        4539=>'VILLA BORJAS',
        13206=>'CUATRO ESQUINAS',
        13207=>'POZO DEL SALADO',
        13=>'ANGACO SUD',
        14=>'LA DIVISORIA',
        15=>'LA MAJADITA',
        537=>'RINCON CERCADO',
        538=>'VILLA CABECERA',
        3131=>'ALTO DE SIERRA',
        3132=>'COLONIA FIORITO',
        3133=>'LAS CHACRITAS',
        3134=>'DE JULIO',
        16=>'ALBARDON CENTRO',
        17=>'LAS LAJAS',
        18=>'LAS LOMITAS',
        19=>'LAS PIEDRITAS',
        20=>'VILLA ALCIRA',
        21=>'VILLA CHILE',
        22=>'VILLA GENERAL SAN MARTÍN - CAMPO AFUERA',
        23=>'VILLA SAN MIGUEL',
        3098=>'EL RINCON',
        4513=>'CAMPO AFUERA',
        4514=>'LA CAÑADA',
        4515=>'VILLA AMPACAMA',
        4516=>'VILLA GENERAL SAN MARTIN',
        6340=>'LAS TAPIAS',
        6341=>'OBISPO ZAPATA',
        6342=>'TIERRA ADENTRO',
        10534=>'EL SALADO',
        10535=>'EL TOPON',
        10536=>'FINCA EL SALADO',
        24=>'AGUILERA',
        25=>'ANGACO CENTRO',
        26=>'BELGRANO',
        27=>'CAMPO DE BATALLA',
        28=>'DIVISORIA',
        29=>'EL ALAMITO',
        30=>'OLIVERA',
        31=>'PLUMERILLO',
        32=>'PUNTA DEL MONTE',
        33=>'VILLA EL SALVADOR - VILLA SEFAIR',
        3099=>'LAS TAPIAS',
        3100=>'LA CAÑADA',
        3101=>'EL BOSQUE',
        4517=>'VILLA EL SALVADOR',
        4518=>'VILLA SEFAIR (TALACASTO)',
        34=>'BARREAL - VILLA PITUIL',
        35=>'BARREALITO',
        36=>'HILARIO',
        37=>'LA ISLA',
        38=>'LA PUNTILLA',
        39=>'PACHACO',
        40=>'PUCHUZUN',
        41=>'SOROCAYENSE',
        42=>'VILLA CORRAL',
        43=>'VILLA NUEVA',
        3102=>'CALINGASTA',
        3103=>'TAMBERIAS',
        3104=>'BARREAL',
        4519=>'VILLA PITUIL',
        6419=>'ALCAPARROSA',
        6420=>'BELLA VISTA',
        6421=>'COLON',
        6422=>'EL LEONCITO',
        6423=>'LA ALUMBRERA',
        6424=>'TIRA LARGA',
        44=>'B. DEL CARMEN',
        45=>'BARRIO CABOT',
        46=>'CONCEPCION',
        47=>'DESAMPARADOS',
        48=>'MEDANO DE ORO',
        49=>'TRINIDAD',
        50=>'VILLA AMERICA',
        51=>'VILLA BARDIANI',
        52=>'VILLA DEL CARRIL',
        728=>'VILLA MALLEA',
        3105=>'SAN JUAN',
        729=>'DIFUNTA CORREA',
        3106=>'BERMEJO',
        3107=>'CAUCETE',
        3108=>'EL RINCON',
        3109=>'MARAYES',
        3110=>'PIE DE PALO',
        3111=>'VALLECITO',
        3112=>'VILLA INDEPENDENCIA',
        3113=>'LAS CHACRAS',
        4520=>'LAS TALAS',
        4521=>'LOS MEDANOS',
        6425=>'DIVISORIA',
        6426=>'LAGUNA SECA',
        8881=>'LAS CHACRAS MARAYES',
        8882=>'LAS LIEBRES',
        8883=>'BARRIO JUSTO P. CASTRO IV',
        12270=>'LA CHILCA',
        12271=>'LA PUNTILLA',
        12272=>'LAS TALAS - LOS MÉDANOS',
        12273=>'LOTES DE ALVAREZ',
        12274=>'NIQUIZANGA',
        12275=>'PAPAGAYO',
        12276=>'POZO DE LOS ALGARROBOS',
        12952=>'AGUADA DE AMPACAMA',
        730=>'CARCEL PUBLICA',
        731=>'VILLA SAN ISIDRO',
        4522=>'CHIMBAS (CHIMBAS)',
        4523=>'EL MOGOTE',
        4524=>'VILLA PAULA ALBARRACIN',
        7614=>'CHIMBAS',
        7615=>'CHIMBAS DEL SUR',
        7616=>'VILLA MORRONES',
        7617=>'VILLA OBRERA',
        8884=>'BARRIO PARQUE IDUSTRIAL',
        8885=>'BARRIO PARQUE INDEPENDENCIA',
        8886=>'VILLA OBSERVATORIO',
        8887=>'VILLA SARMIENTO',
        8888=>'VILLA UNION',
        732=>'CAMPANARIO',
        733=>'GUAÑIZUIL',
        734=>'TAMBILLOS',
        735=>'TOCOTA',
        736=>'VILLA IGLESIA',
        738=>'ZONDA ',
        1744=>'EL RETIRO',
        3114=>'ANGUALASTO',
        3115=>'BELLA VISTA',
        3116=>'IGLESIA',
        3117=>'LAS FLORES',
        3118=>'PISMANTA',
        3119=>'RODEO',
        3120=>'TUDCUM',
        5586=>'COLANGUIL',
        5587=>'COLOLA',
        6263=>'ARREQUINTIN',
        6899=>'MALIMAN DE ABAJO',
        8889=>'ACHANGO',
        8890=>'BAUCHACETA',
        8891=>'FIERRO NUEVO',
        8892=>'FIERRO VIEJO',
        8893=>'GUARDIA VIEJA',
        8894=>'MALIMAN DE ARRIBA',
        12879=>'MONDACA',
        12880=>'ZONDA',
        306=>'BELLA VISTA',
        307=>'BOCA DE LA QUEBRADA',
        308=>'DIQUE PACHIMOCO',
        309=>'EL VOLCAN',
        310=>'GUALCAMAYO',
        311=>'INDIO MUERTO',
        312=>'LA FRONTERA',
        313=>'LA TOMA',
        314=>'LAS AGUADITAS',
        315=>'LOS PUESTOS',
        316=>'NIQUIVIL VIEJO',
        317=>'OTRA BANDA',
        318=>'PANACAN',
        654=>'EL FISCAL',
        737=>'ADAN QUIROGA',
        739=>'AGUA HEDIONDA',
        740=>'AGUADA',
        741=>'CRUZ DE PIEDRA',
        742=>'EL BALDE',
        743=>'EL PANTANILLO',
        744=>'ENTRE RIOS',
        745=>'HUALLARA',
        746=>'HUERTA DE HUACHI',
        747=>'JACHAL CENTRO',
        748=>'JARILLAS',
        749=>'LA CIENAGA',
        750=>'LA CIENEGUITA',
        751=>'LA REPRESA',
        752=>'PACHIMOCO',
        753=>'PAMPA DEL CHAÑAR',
        754=>'PAMPA VIEJA',
        755=>'PUNTA DEL AGUA',
        756=>'RINCON',
        757=>'SAN ROQUE',
        3121=>'EL MEDANO',
        3122=>'GRAN CHINA',
        3123=>'HUACO',
        3124=>'MOGNA',
        3125=>'NIQUIVIL',
        3126=>'SAN ISIDRO',
        3127=>'SAN JOSE DE JACHAL',
        3128=>'TAMBERIAS',
        3129=>'VILLA MALVINAS ARGENTINAS',
        3130=>'VILLA MERCEDES',
        4525=>'EL FICAL',
        4526=>'LA FALDA',
        4527=>'PAMPA VIEJA (PAMPA VIEJA)',
        539=>'ESTACION SANCHEZ DE LORIA',
        540=>'LA CALLECITA',
        541=>'SEGUNDO CUARTEL',
        542=>'VILLA AEROPUERTO',
        543=>'BARRIO MUNICIPAL',
        544=>'LAS PIEDRITAS',
        758=>'CAMPO DE BATALLA',
        759=>'CERRILLO',
        760=>'COLONIA ROCA',
        761=>'KILOMETRO ',
        1437=>'MEDANO DE ORO',
        1438=>'POCITO',
        1439=>'SANCHEZ DE LORIA',
        1440=>'VILLA ABERASTAIN - LA RINCONADA',
        1441=>'VILLA BARBOZA - VILLA NACUSI',
        1442=>'VILLA CREMADES',
        1443=>'VILLA LIBERTAD',
        1444=>'VILLA LIZA',
        3135=>'BARRIO RUTA ',
        3136=>'CARPINTERIA',
        3137=>'QUINTO CUARTEL',
        3138=>'VILLA CENTENARIO',
        3139=>'COLONIA RODAS',
        3140=>'EL ABANICO',
        4528=>'LA RINCONADA',
        4529=>'VILLA ABERASTAIN',
        4530=>'VILLA BARBOZA',
        4531=>'VILLA NACUSI',
        6904=>'COLONIA CANTONI',
        1445=>'B. ATLETICO',
        1446=>'B. BELGRANO',
        1447=>'B. GUEMES',
        1448=>'B. NEUQUEN',
        1449=>'B. SARMIENTO',
        1450=>'B.S.M.DEL CARRIL',
        1451=>'BARRIO C.BUSTOS',
        1452=>'BARRIO CAPITAN LAZO',
        1453=>'BARRIO FERROVIARIO',
        1454=>'BARRIO SAN LUIS',
        1455=>'CAPITAN LAZO',
        1456=>'COLONIA MEDANO DE ORO',
        1457=>'COLONIA ROSALES',
        1458=>'RAWSON',
        1459=>'VILLA BURON ALONZO',
        1460=>'VILLA ELISA',
        1461=>'VILLA ESTORNELL',
        1462=>'VILLA GUSMAN',
        1463=>'VILLA HIPODROMO',
        1464=>'VILLA ITALIA',
        1465=>'VILLA LAPLAGNE',
        1466=>'VILLA LAS ROSAS',
        1467=>'VILLA LERGA',
        1468=>'VILLA LLIVER',
        1469=>'VILLA OBRERA',
        1470=>'VILLA SAN DAMIAN',
        1471=>'VILLA SAN RICARDO',
        3141=>'VILLA BOLAÑOS',
        4532=>'EL MEDANITO',
        4533=>'RAWSON (RAWSON)',
        4534=>'VILLA KRAUSE',
        8825=>'COLONIA PAN DE AZUCAR',
        8826=>'COLONIA RODAS',
        8827=>'LOS CORREDORES',
        1472=>'B. FOEVA',
        1473=>'B.SUB-OFICIALES',
        1474=>'BARRIO RIVADAVIA',
        1475=>'BARRIO VILLA DEL CAR',
        1476=>'LA BEBIDA',
        1477=>'MARQUESADO',
        1478=>'PUNTILLA BLANCA',
        1479=>'VILLA FLORA',
        1480=>'VILLA HUAZIHUL',
        1481=>'VILLA LOURDES',
        1482=>'VILLA OBRERA',
        1483=>'VILLA R.PINTO',
        1484=>'VILLA SAN FRANCISCO',
        1485=>'VILLA SAN ROQUE',
        2161=>'VILLA SANTA ANITA',
        2162=>'VILLA SANTA INES',
        2163=>'ZONDA',
        3142=>'RIVADAVIA',
        12945=>'BARRIO CAMUS',
        12946=>'BARRIO FORTABAT',
        12947=>'JARDIN DE LOS POETAS',
        12948=>'VILLA NUEVA ARGENTINA',
        2164=>'DOS ACEQUIAS',
        2165=>'LA PUNTILLA',
        2166=>'LA PUNTILLA BLANCA',
        2167=>'LA PUNTILLA NEGRA',
        2168=>'LOS ANGACOS',
        2169=>'SAN MARTIN',
        2170=>'VILLA LUGANO',
        2171=>'VILLA LUJAN',
        3143=>'BARRIO SADOP',
        3144=>'DOS ACEQUIAS (EST. LOS ANGACOS)',
        3145=>'SAN ISIDRO',
        3146=>'VILLA EL SALVADOR',
        3147=>'VILLA DOMINGUITO',
        3148=>'VILLA DON BOSCO',
        3149=>'VILLA SAN MARTIN',
        12949=>'BOCA DEL TIGRE',
        12950=>'LOS COMPARTOS',
        1746=>'LAS PIEDRITAS',
        2172=>'COLONIA RICHET ZAPATA',
        2173=>'COLONIA ZAPATA',
        2174=>'LA LEGUA',
        2175=>'SANTA LUCÍA',
        2176=>'TIERRA ADENTRO',
        2177=>'VILLA CAMPODONICO',
        2178=>'VILLA DON ARTURO',
        2179=>'VILLA MARINI',
        2180=>'VILLA SAN EDUARDO',
        3150=>'COLONIA GUTIERREZ',
        4535=>'ALTO DE SIERRA',
        4536=>'SANTA LUCÍA (COLONIA GUTIÉRREZ)',
        4537=>'SANTA LUCIA',
        12951=>'BARRIO BERMEJITO',
        2181=>'BARRIO PATIÑO',
        2182=>'CIENAGA',
        2183=>'COLONIA SAN ANTONIO',
        2184=>'DURAZNO',
        2185=>'ESTACION COCHAGUAL',
        2186=>'RETAMITO',
        2187=>'SAN CARLOS',
        2188=>'TRES ESQUINAS',
        2189=>'VILLA SARMIENTO',
        3151=>'CAÑADA HONDA',
        3152=>'CIENAGUITA',
        3153=>'COLONIA FISCAL',
        3154=>'DIVISADERO',
        3155=>'GUANACACHE',
        3156=>'LAS LAGUNAS',
        3157=>'LOS BERROS',
        3158=>'PEDERNAL',
        3159=>'PUNTA DEL MEDANO',
        3160=>'VILLA MEDIA AGUA',
        3161=>'COCHAGUAL NORTE',
        3162=>'COCHAGUAL CENTRO',
        3163=>'LA CILVICA',
        2190=>'DIQUE ULLUM',
        2191=>'EL CHILOTE',
        2192=>'PACHACO',
        3164=>'VILLA IBAÑEZ',
        1751=>'SANTO DOMINGO',
        2193=>'AGUA CERCADA',
        2194=>'BALDE DE ASTICA',
        2195=>'LA CIENAGUITA',
        2196=>'BALDES DE LA CHILCA',
        2197=>'LAS JUNTAS',
        2198=>'BALDES DEL SUD',
        2199=>'CHUCHILLACO',
        2875=>'LOS MOLLES',
        2876=>'MAJADITA',
        2877=>'PASTO BLANCO',
        2878=>'SANTA ROSA',
        2879=>'SIERRA DE CHAVES',
        2880=>'VALLE FERTIL',
        2881=>'YOCA',
        3165=>'ASTICA',
        3166=>'BALDE DEL ROSARIO',
        3167=>'CHUCUMA',
        3168=>'LOS BALDECITOS',
        3169=>'USNO',
        3170=>'VILLA SAN AGUSTIN',
        3171=>'LAS TUMANAS',
        3172=>'SAN ANTONIO',
        3173=>'SIERRA DE RIVERO',
        3174=>'LOMAS BLANCAS',
        3175=>'SIERRA DE ELIZONDO',
        3176=>'LOS RINCONES',
        3177=>'BUENA ESPERANZA',
        3178=>'LAS FLORES',
        3179=>'QUEBRADA DE USNO',
        3180=>'SIERRA DE CHÁVEZ',
        3181=>'LA MAJADITA',
        3182=>'BALDES DE LAS CHILCAS',
        3183=>'BALDES DEL SUR',
        3184=>'BALDES DE ASTICA',
        3185=>'LA MESADA',
        13201=>'BALDES DEL NORTE',
        13202=>'COLONIA LOS VALECIANOS',
        13203=>'LA HUERTA',
        13204=>'LOS BRETES',
        13205=>'RINCON CHICO',
        448=>'LOS PARAMILLOS',
        449=>'PACHACO',
        2882=>'CERRO BLANCO',
        2883=>'VILLA BASILIO NIEVAS',
        2884=>'ZONDA ARRIBA',
        2885=>'ZONDA CENTRO',
        4540=>'VILLA BASILIO NIEVAS  (VILLA BASILIO NIEVAS)',
        4541=>'VILLA TACU'

    );

    return $loc[$locNumero];
}